### ISSUE TITLE
Release 4.8

### ISSUE THREAD

**Issue by xambroz** [urbanadventurer/WhatWeb#118]
Hello,
please do you plan to tag a 4.8 release at some point?
It would make it easier to the package managers in various Linux distributions to package your software. 

Thank you
Michal Ambroz

**Comment by xambroz** [comment]
16 months later, still no release tag

**Comment by gcsideal** [comment]
Hi,
I'm the Debian maintainer of WhatWeb. While it would be nicer to use simple version numbers, to date nothing prevented me to package this software. Please see: https://packages.qa.debian.org/w/whatweb.html

**Comment by xambroz** [comment]
Hi,
I am trying to get it to Fedora as well .... https://bugzilla.redhat.com/show_bug.cgi?id=whatweb
But the version is ugly right? Not mentioning that I get just randomly to pickup the snapshot from the git not really knowing whether it would not be better to take the snapshot day after.
Mik

**Comment by fgeek** [comment]
In my opinion this is very important point:
```
Not mentioning that I get just randomly to pickup the snapshot from the git not really knowing whether it would not be better to take the snapshot day after.
```
Of course there should be unittests to avoid problems, but project developer and/or maintainer should be the entity to tell, which version is ready for "production use".

**Comment by gcsideal** [comment]
@xambroz : you can always check the Git history, why and what has been changed. You can decide if the changes are important enough to do a new package version. I don't think that the version number is ugly. It's short enough while being descriptive. But yes, a timely release often helps.
@fgeek : sure, the package maintainer should know the distribution environment s/he works for, if an upstream change is a mandatory for the system (for example a Ruby support commit) or just a small feature addition (for example to detect a very rare NTP server version). Then backport the relevant changes to the tagged version (0.4.7) or package the current Git version. Of course, users can vote via the distribution bug tracker: 'Please package a newer version because it has support for xy'.

**Comment by urbanadventurer** [comment]
I hear what you're saying and I've updated to version 0.4.9.
